name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckOut code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: login on DockerHub
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        echo "Iniciando logIn"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del logIn"
    - name: Build docker image
      run: |
        docker build -t fernando26dev/docker-githubactions:1.0.1 .
    - name: Push docker image
      run: |
        docker push fernando26dev/docker-githubactions:1.0.1
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
