name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckOut code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with: 
        major_patter: "major:"
        minor_patter: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version  

    - name: login on DockerHub
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        echo "Iniciando logIn"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del logIn"
        
    - name: Build docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
       docker build -t fernando26dev/docker-githubactions:$NEW_VERSION .
       docker build -t fernando26dev/docker-githubactions:latest .
       echo "version: $ NEW_VERSION"
    
    - name: Push docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push fernando26dev/docker-githubactions:$NEW_VERSION
        docker push fernando26dev/docker-githubactions:latest
        echo "version: $ NEW_VERSION"
    
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
